language: node_js

node_js:
  - node
  - 10

env:
 - scr: 'npm install -g react-360-cli'
 - scr: 'pushd website && npm install && popd'
 - scr: 'pushd react-360-cli && npm install && popd'

install:
    ## dependencies ##
    - node scripts/install-deps.js
 
script:
     - $src
